version: "2.4"
services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: .
    volumes:
      - ./package.json:/opt/package.json
      - ./lib/:/opt/lib/
      - ./run.sh:/opt/run.sh
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: curl -sS -m 5 http://127.0.0.1:3000/http://127.0.0.1:3000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
